torch_seed: 123
project_name: "arcface-pytorch"  # wandb project name
run_name: "best_config"  # wandb run name

env: "default"
backbone: "resnet18"
classify: "softmax"
num_classes: 43
metric: "arc_margin"
easy_margin: False
use_se: False
loss: "focal-loss"

display: False
finetune: False

train_root: "../arcface-tf2/data/graph_data_augmented"

test_root: "/data1/Datasets/anti-spoofing/test/data_align_256"
test_list: "test.txt"

checkpoints_path: "checkpoints"
load_model_path: "models/resnet18.pth"
test_model_path: "checkpoints/12/resnet18 best_.pth"
save_interval: !!int 10

#infer_file_path: "../graphClassification/graph_data_original"
infer_file_path: ['../graphClassification/graph_data_original/0/125183_graph 0.87.png', '../graphClassification/graph_data_original/0/303223_graph 0.88.png']
train_batch_size: !!int 64  # batch size
test_batch_size: !!int 64

input_shape: (1, 256, 256)

optimizer: "sgd"

use_gpu: True  # use GPU or not
gpu_id: "0, 1"
num_workers: !!int 8  # how many workers for loading data
print_freq: !!int 100  # print info every N batch

debug_file: "/tmp/debug"  # if os.path.exists(debug_file): enter ipdb
result_file: "result.csv"

max_epoch: !!int 30
lr: !!float 3e-3  # initial learning rate
lr_step: !!int 10
lr_decay: !!float 0.7  # when val_loss increase, lr: lr*lr_decay
weight_decay: !!float 5e-1

clipping: False # Gradient clipping
clipping_max_norm: 5

size : None # ori, s(small), xs, None(if pretrained)
pretrained: True # Use pretrained model?

dr_rate: False
cross_validation: False